# Netlify configuration for Org Chart Plugin

[build]
  # Build command
  command = "npm run build"
  
  # Directory with the built files
  publish = "dist"
  
  # Node version for build environment
  [build.environment]
    NODE_VERSION = "18"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and CORS
[[headers]]
  for = "/*"
  [headers.values]
    # Allow CORS for Sigma Computing
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    
    # Allow iframe embedding from Sigma Computing
    Content-Security-Policy = "frame-ancestors https://*.sigmacomputing.com"
    
    # Security headers
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Build optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = false

[build.processing.images]
  compress = true